export const dummyData = [
  {
    id: 1,
    name: "Dr. Madhukar",
    specialization: "Gynecologist",
    experience: "12 years",
    available_days: ["Tue", "Thu", "Fri", "Sat"],
    timing: "10:00 AM - 01:00 PM",
    fee: "Rs. 300",
  },
  {
    id: 2,
    name: "Dr. Aditi Sharma",
    specialization: "Pediatrician",
    experience: "8 years",
    available_days: ["Mon", "Wed"],
    timing: "09:00 AM - 12:00 PM",
    fee: "Rs. 250",
  },
  {
    id: 3,
    name: "Dr. Rohan Mehta",
    specialization: "Cardiologist",
    experience: "15 years",
    available_days: ["Mon", "Fri", "Sat"],
    timing: "11:00 AM - 02:00 PM",
    fee: "Rs. 500",
  },
  {
    id: 4,
    name: "Dr. Pooja Nair",
    specialization: "Dermatologist",
    experience: "10 years",
    available_days: ["Wed", "Sat"],
    timing: "10:00 AM - 01:00 PM",
    fee: "Rs. 300",
  },
  {
    id: 5,
    name: "Dr. Arjun Kapoor",
    specialization: "Orthopedic Surgeon",
    experience: "18 years",
    available_days: ["Tue", "Fri"],
    timing: "12:00 PM - 03:00 PM",
    fee: "Rs. 400",
  },
  {
    id: 6,
    name: "Dr. Sneha Verma",
    specialization: "ENT Specialist",
    experience: "9 years",
    available_days: ["Mon", "Thu"],
    timing: "10:00 AM - 12:30 PM",
    fee: "Rs. 350",
  },
  {
    id: 7,
    name: "Dr. Abhishek Rao",
    specialization: "Neurologist",
    experience: "14 years",
    available_days: ["Wed", "Fri"],
    timing: "11:00 AM - 02:00 PM",
    fee: "Rs. 600",
  },
  {
    id: 8,
    name: "Dr. Priya Malhotra",
    specialization: "Psychiatrist",
    experience: "11 years",
    available_days: ["Tue", "Thu"],
    timing: "09:00 AM - 12:00 PM",
    fee: "Rs. 400",
  },
  {
    id: 9,
    name: "Dr. Karan Singh",
    specialization: "Urologist",
    experience: "16 years",
    available_days: ["Mon", "Wed"],
    timing: "10:30 AM - 01:30 PM",
    fee: "Rs. 450",
  },
  {
    id: 10,
    name: "Dr. Meera Patel",
    specialization: "Endocrinologist",
    experience: "13 years",
    available_days: ["Tue", "Fri"],
    timing: "11:00 AM - 01:00 PM",
    fee: "Rs. 500",
  },
  {
    id: 11,
    name: "Dr. Rajat Khanna",
    specialization: "Oncologist",
    experience: "20 years",
    available_days: ["Mon", "Thu"],
    timing: "10:00 AM - 12:00 PM",
    fee: "Rs. 700",
  },
  {
    id: 12,
    name: "Dr. Shalini Gupta",
    specialization: "Ophthalmologist",
    experience: "10 years",
    available_days: ["Wed", "Fri"],
    timing: "09:30 AM - 12:30 PM",
    fee: "Rs. 300",
  },
  {
    id: 13,
    name: "Dr. Ankit Jain",
    specialization: "Gastroenterologist",
    experience: "17 years",
    available_days: ["Tue", "Thu"],
    timing: "12:00 PM - 03:00 PM",
    fee: "Rs. 550",
  },
  {
    id: 14,
    name: "Dr. Neha Desai",
    specialization: "Pulmonologist",
    experience: "12 years",
    available_days: ["Mon", "Fri"],
    timing: "10:00 AM - 01:00 PM",
    fee: "Rs. 400",
  },
  {
    id: 15,
    name: "Dr. Vivek Kumar",
    specialization: "Nephrologist",
    experience: "14 years",
    available_days: ["Wed", "Sat"],
    timing: "11:00 AM - 02:00 PM",
    fee: "Rs. 600",
  },
  {
    id: 16,
    name: "Dr. Reena Kapoor",
    specialization: "Rheumatologist",
    experience: "13 years",
    available_days: ["Tue", "Thu"],
    timing: "09:00 AM - 12:00 PM",
    fee: "Rs. 450",
  },
  {
    id: 17,
    name: "Dr. Gaurav Sharma",
    specialization: "Plastic Surgeon",
    experience: "19 years",
    available_days: ["Mon", "Wed"],
    timing: "11:00 AM - 01:30 PM",
    fee: "Rs. 800",
  },
  {
    id: 18,
    name: "Dr. Ritu Ahuja",
    specialization: "Radiologist",
    experience: "15 years",
    available_days: ["Tue", "Fri"],
    timing: "10:00 AM - 12:30 PM",
    fee: "Rs. 500",
  },
  {
    id: 19,
    name: "Dr. Akash Pandey",
    specialization: "Hematologist",
    experience: "16 years",
    available_days: ["Mon", "Thu"],
    timing: "12:00 PM - 02:00 PM",
    fee: "Rs. 550",
  },
  {
    id: 20,
    name: "Dr. Sanjana Nair",
    specialization: "Allergist",
    experience: "9 years",
    available_days: ["Wed", "Fri"],
    timing: "09:00 AM - 12:00 PM",
    fee: "Rs. 350",
  },
];
