import SideNav from "@/components/home/SideNav";
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import { useForm, Controller } from "react-hook-form"
import { Appointment } from "@/schema"
import { useState, useTransition } from "react"
import { book } from "@/actions/appoint"
import FormSuccess from "@/components/auth/form-sucess"
import FormError from "@/components/auth/form-error"
import { FaEnvelope, FaPhone, FaCalendarAlt, FaTelegram } from "react-icons/fa"